---
title: "Bad weather Kelheim Demo"
author: "Oleksandr Soboliev"
output:
  html_document:
    df_print: paged
  html_notebook:
    theme: cosmo
    highlight: monochrome
    code_folding: show
runtime: shiny
editor_options:
  chunk_output_type: inline
---

```{r, include= FALSE}
library(tidyverse)
library(lubridate)
library(plotly)
library(leaflet)
library(rmarkdown)
library(modelr)
library(splines)
library(forecast)
library(fitdistrplus)
library(rjson)

if ("fitdistrplus" %in% (.packages())){
  detach(package: fitdistrplus, unload = TRUE)
}

if ("fitdistrplus" %in% (.packages())){
  detach(package: MASS, unload = TRUE)
}

if ("fitdistrplus" %in% (.packages())){
  detach(package: stats, unload = TRUE)
}

knitr::opts_chunk$set(echo = TRUE)
```

Approach to build a daily model
## **Import weather**
```{r import weather}
ingolstadt_weather = read_delim("https://bulk.meteostat.net/v2/daily/10860.csv.gz",",",col_names = FALSE)

colnames(ingolstadt_weather) = c("date", "tavg", "tmin", "tmax", "prcp", "snow", "wdir", "wspd", "wpgt", "pres", "tsun")


# We don't need data of weather before 2020, because of snz_mobility date, also data isn't precise

ingolstadt_weather = ingolstadt_weather %>% filter(year(date)>=2020)%>% replace_na(list(snow = 0))


# To get description
weatherstack_kelheim = read_delim("data/Kelheim_weather_since_july_2008.csv",delim = ",")
weatherstack_kelheim_daily = weatherstack_kelheim %>%
  group_by(date) %>%
  count(description)
```

## **Add stringency of covid policies to a data**
```{r import}
json = fromJSON(file = "data/2022-10-08.json")
unlisted_json = unlist(json)
```

```{r}
deu_stringency = unlisted_json[grep("DEU.stringency_actual",names(unlisted_json))]
date_stringency = sapply(strsplit(names(deu_stringency),split = ".",fixed = TRUE),"[[",2)
df_stringency = data.frame(date = date_stringency,stringency = deu_stringency)
df_stringency = df_stringency %>% mutate(stringency = as.numeric(stringency), date = as.Date(date))
```
## **Import mobility**
```{r import mobility}
demand = read_delim("data/allDemandByDate.csv")

```
## **Import holidays**
```{r}
holidays2020 = read_csv2("data/Holidays2020.csv") %>% dplyr::select(1,2,3)
holidays2021 = read_csv2("data/Holidays2021.csv") %>% dplyr::select(1,2,3)
holidays2022 = read_csv2("data/Holidays2022.csv") %>% dplyr::select(1,2,3)
holidays = rbind(holidays2020,holidays2021,holidays2022)
holidays = holidays %>% mutate(EndDateTime1 = as.Date(mdy_hm(EndDateTime1)),
                               StartDateTime1 = as.Date(mdy_hm(StartDateTime1)))

holiday_days = c(seq(holidays$StartDateTime1[1],holidays$EndDateTime1[1],by = "days"))

for(i in 1:nrow(holidays)){
  holiday_days = append(holiday_days,seq(holidays$StartDateTime1[i],holidays$EndDateTime1[i],by = "days"))
}

df_holidays = data.frame(date = holiday_days,isHoliday = TRUE)

```
## **Modify data**

```{r modify data}
type_of_weather = unique(weatherstack_kelheim$description)
map_vector <- c("Clear","Sunny","Cloudy","Light","Light","Light","Light","Light","Light","Light","Light","Medium","Cloudy","Light","Light","Heavy","Heavy","Heavy","Light","Medium","Heavy","Heavy","Light","Heavy","Heavy","Heavy","Heavy","Heavy","Heavy","Light","Medium","Medium","Light","Heavy","Light","Light","Light","Light","Light","Heavy","Light","Medium","Heavy","Heavy","Heavy")
names(map_vector)<- type_of_weather




ingolstadt_weather = ingolstadt_weather %>% 
  mutate(season = ifelse(month(date) %in% c(12,1,2),"winter",NA)) %>%
  mutate(season = ifelse(month(date) %in% c(3,4,5),"spring",season)) %>%
  mutate(season = ifelse(month(date) %in% c(6,7,8),"summer",season)) %>%
  mutate(season = ifelse(month(date) %in% c(9,10,11),"autumn",season))# %>% dplyr::select(-tsun)




day_description_impact = weatherstack_kelheim_daily %>% pivot_wider(names_from = description,values_from = n)

#remove NAs
day_description_impact[is.na(day_description_impact)] = 0

day_description_impact = day_description_impact %>% pivot_longer(cols = all_of(type_of_weather),names_to = "description",values_to = "value")

day_description_impact = day_description_impact
day_description_impact$description = map_vector[(day_description_impact$description)]

day_description_impact= day_description_impact %>% group_by(date)%>%
  top_n(n = 1,value) %>% group_by(date) %>% top_n(n = 1,description) %>% rename(weather_impact = value)
```

## **Join all data together**
```{r join data}
result_data = demand %>% inner_join(day_description_impact, by = "date") %>% inner_join(ingolstadt_weather,by = "date") %>% inner_join(df_stringency,by = "date") %>% mutate(date = as.Date(date,format = "%Y-%m-%d"))
#Also need to be added weekday
result_data = result_data %>% mutate(wday = as.character(wday(date,week_start = 1)))

#Append holidays
result_data = result_data %>% left_join(df_holidays, by = "date") %>% replace_na(list(isHoliday = FALSE)) #%>% filter(noRides != 0) #%>% filter(date <"2021-07-01")

```

```{r best predictors, echo=FALSE}
best_pred <- result_data  %>% ungroup() %>%
  dplyr::select(-noRides,-description ,-date,-season,-noRequests,-avgEuclidianDistance_m,-avgTravelTime_s,-wday) %>%
  map_dbl(cor,y = result_data$noRides) %>%
  #map_dbl(abs) %>%
  sort(decreasing = TRUE) 
print(best_pred)
```

```{r best predictors without predictors, echo=FALSE}
pred_data = result_data %>%filter(isHoliday==FALSE, wday != 6 , wday!=7,noRides !=0)
best_pred <- pred_data %>% ungroup() %>%
  dplyr::select(-noRides,-description ,-date,-season,-noRequests,-avgEuclidianDistance_m,-avgTravelTime_s,-wday) %>%
  map_dbl(cor,y = pred_data$noRides) %>%
  #map_dbl(abs) %>%
  sort(decreasing = TRUE) 
print(best_pred)
```

## **Build a model**
```{r}
data = pred_data 
demand_model = lm(noRides ~ ns(tavg,1)+pres++date+stringency+wday+snow,data = data)
reduced.model = step(demand_model,direction = "backward")

human_model = lm(noRides ~ tavg+pres+stringency+wday+isHoliday+description*weather_impact+snow+prcp,data = data)

#summary(human_model)
summary(demand_model)
#summary(reduced.model)
```

## **Draw a plot**
```{r predictions}
colors = c("actual" = "blue","predicted" = "red","residuals" = "gray50","zerorides" = "purple")
model = demand_model
test_data = data %>% add_predictions(model = model) %>% add_residuals(model = model) %>% mutate(error = ifelse(abs(resid)>=20,"extreme","normal"))

#Ask ifwe should conclude this data to our analysis
zerorides = test_data %>% filter(noRides == 0)

ggplotly(ggplot(test_data %>% filter(year(date)>=2020)) +
  geom_line(aes(x = date,y = noRides,color = "actual"))+
  geom_line(aes(x = date,y = pred,color = "predicted"))+
  geom_line(aes(x = date,y = resid,color = "residuals"))+
  #geom_point(data = zerorides,aes(x = date,y = resid,color = "zerorides"))+
  geom_ref_line(h = 0)+
  scale_color_manual(values = colors))

```
root mean square
mean absolute error
residual
outliers in qqplot


```{r}
barplot <- ggplot(test_data, aes(x = resid ))+
  geom_histogram(aes(y = stat(density)),colour="black", fill="white", binwidth=7)+
  geom_density( fill="#FF6666",adjust = 10,alpha = 0.5) 


ggplotly(barplot)
```

```{r residuals verteilung}
fitdistrplus::descdist(test_data$resid)
```

```{r}
normal_dist = fitdistrplus::fitdist(test_data$resid,"norm")
plot(normal_dist)
```
```{r}
shapiro.test(test_data$resid)
```

1 by 1 plots
```{r wday}
ggplot(result_data)+
  geom_boxplot(aes(x = wday,y = noRides,colour = season ))
```
estimate extremely high residual values
```{r}
high_values = test_data %>% mutate(type = ifelse(abs(resid)>=20,"extreme","normal"))


```

```{r tavg}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = tavg,colour = type,shape = isHoliday))
```

```{r tavg with season}
ggplotly(ggplot(high_values)+
  geom_point(aes(y = noRides,x = tavg,colour = type,shape = season)))
```


```{r tmax}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = tmax,colour = type,shape = isHoliday))
```

```{r prcp}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = prcp,colour = type,shape = isHoliday))
```

```{r snow}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = snow,colour = type,shape = isHoliday))
```

```{r wdir}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = wdir,colour = type,shape = isHoliday))
```

```{r wspd}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = wspd,colour = type,shape = isHoliday))
```


```{r pres}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = pres,colour = type,shape = isHoliday))
```

```{r stringency}
ggplot(high_values)+
  geom_point(aes(y = noRides,x = stringency,colour = type,shape = isHoliday))
```
